language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

## Non-sudo environments are faster
sudo: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer config github-oauth.github.com "${GITHUB_OAUTH_TOKEN}"
  - travis_retry composer update

script:
  - phpunit --coverage-clover tests/clover.xml

after_script:
  - php vendor/bin/coveralls -v
